version: "3"
services:
  web:
    image: nginx:latest
    restart: always 
    ports:
      - "8080:80"
    volumes:
      - ./websites:/usr/share/nginx/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD="$MYSQL_password"
    volumes:
      - db_vol:/var/lib/mysql
volumes:
  db_vol:
